/*
 * This source file was generated by the Gradle 'init' task
 */
package org.wiredcats;

import edu.wpi.first.math.geometry.Rectangle2d;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;

public class TargetCalculations {
    public Rectangle2d targetGoalRegion; 
    public Pose2d target; 
    public double targetHeight = 0.0;

    public Pose2d leftPassingTarget; 
    public Pose2d rightPassingTarget; 
    public Pose2d middlePassingTarget; 

    // should be passed in radians and measured from vertical
    public double passingLaunchAngle; 
    public double targetLaunchAngle; 

    /* CONSTRUCTORS */
    /* targetGoalRegion should be defined in meters for all of these */
    // when you already have a target goal region specific to your alliance and have a defined left, right, and middle passing region
    public TargetCalculations(Rectangle2d targetGoalRegion, Pose2d target, double targetHeight, Pose2d leftPassingTarget, Pose2d rightPassingTarget, Pose2d middlePassingTarget, double passingLaunchAngle, double targetLaunchAngle) {
        this.targetGoalRegion = targetGoalRegion; 
        this.target = target; 
        this.targetHeight = targetHeight;
        this.leftPassingTarget = leftPassingTarget; 
        this.rightPassingTarget = rightPassingTarget; 
        this.middlePassingTarget = middlePassingTarget; 
        this.passingLaunchAngle = passingLaunchAngle; 
        this.targetLaunchAngle = targetLaunchAngle; 
    }

    // when you already have a target goal region specific to your alliance but want passing to automatically be the middle x of the targetGoalRegion and the y to be the middle on the left half and the middle on the right half of the field (center at the middle of the targetGoalRegion).
    public TargetCalculations(Rectangle2d targetGoalRegion, Pose2d target, double targetHeight, double passingLaunchAngle, double targetLaunchAngle) {
        this.targetGoalRegion = targetGoalRegion; 
        this.target = target; 
        this.targetHeight = targetHeight;
        this.passingLaunchAngle = passingLaunchAngle;
        this.targetLaunchAngle = targetLaunchAngle;
        // calculate left and right target locations
        Pose2d calculatedLeftPassingTarget = new Pose2d(targetGoalRegion.getCenter().getX(), targetGoalRegion.getCenter().getY() * 0.5, new Rotation2d(0, 0));
        Pose2d calculatedRightPassingTarget = new Pose2d(targetGoalRegion.getCenter().getX(), targetGoalRegion.getCenter().getY() * 1.5, new Rotation2d(0, 0));

        this.leftPassingTarget = calculatedLeftPassingTarget; 
        this.rightPassingTarget = calculatedRightPassingTarget; 
        this.middlePassingTarget = targetGoalRegion.getCenter(); 
    }

    // when you already have a target goal region specific to your alliance and only have a single passing target
    public TargetCalculations(Rectangle2d targetGoalRegion, Pose2d target, double targetHeight, Pose2d passingTarget, double passingLaunchAngle, double targetLaunchAngle) {
        this.targetGoalRegion = targetGoalRegion; 
        this.target = target; 
        this.targetHeight = targetHeight;
        this.passingLaunchAngle = passingLaunchAngle;
        this.targetLaunchAngle = targetLaunchAngle;
        // set all to center of targetGoalRegion
        this.leftPassingTarget = passingTarget; 
        this.rightPassingTarget = passingTarget; 
        this.middlePassingTarget = passingTarget; 
    }

    // when you have the targetGoalRegion for blue, but your alliance could be red or blue. 
    // this constructor assumes field dimensions from the last year this was updated (2026, for Rebuilt).
    // if you have different field dimensions and this package has not yet been updated, use the next constructor.
    public TargetCalculations(Rectangle2d targetGoalRegion, Pose2d target, double targetHeight, String alliance, double passingLaunchAngle, double targetLaunchAngle) {
        Object[] regionAndTarget = getGoalRegionForAlliance(targetGoalRegion, target, 651.22 / 39.3701, alliance);
        this.targetGoalRegion = (Rectangle2d)regionAndTarget[0];
        this.target = (Pose2d)regionAndTarget[1];
        this.targetHeight = targetHeight;
        this.passingLaunchAngle = passingLaunchAngle;
        this.targetLaunchAngle = targetLaunchAngle;
        // calculate left and right target locations
        Pose2d calculatedLeftPassingTarget = new Pose2d(this.targetGoalRegion.getCenter().getX(), this.targetGoalRegion.getCenter().getY() * 0.5, new Rotation2d(0, 0));
        Pose2d calculatedRightPassingTarget = new Pose2d(this.targetGoalRegion.getCenter().getX(), this.targetGoalRegion.getCenter().getY() * 1.5, new Rotation2d(0, 0));
        this.leftPassingTarget = calculatedLeftPassingTarget;
        this.rightPassingTarget = calculatedRightPassingTarget;
        this.middlePassingTarget = this.targetGoalRegion.getCenter();
    }

    // field width should be passed in meters
    public TargetCalculations(Rectangle2d targetGoalRegion, Pose2d target, double targetHeight, double fieldWidth, String alliance, double passingLaunchAngle, double targetLaunchAngle) {
        Object[] regionAndTarget = getGoalRegionForAlliance(targetGoalRegion, target, fieldWidth, alliance);
        this.targetGoalRegion = (Rectangle2d)regionAndTarget[0];
        this.target = (Pose2d)regionAndTarget[1];
        this.targetHeight = targetHeight;
        this.passingLaunchAngle = passingLaunchAngle;
        this.targetLaunchAngle = targetLaunchAngle;
        // calculate left and right target locations
        Pose2d calculatedLeftPassingTarget = new Pose2d(this.targetGoalRegion.getCenter().getX(), this.targetGoalRegion.getCenter().getY() * 0.5, new Rotation2d(0, 0));
        Pose2d calculatedRightPassingTarget = new Pose2d(this.targetGoalRegion.getCenter().getX(), this.targetGoalRegion.getCenter().getY() * 1.5, new Rotation2d(0, 0));
        this.leftPassingTarget = calculatedLeftPassingTarget;
        this.rightPassingTarget = calculatedRightPassingTarget;
        this.middlePassingTarget = this.targetGoalRegion.getCenter();
    }

    /* INTERNAL HELPER METHODS */
    // handles alliance flipping
    private static Object[] getGoalRegionForAlliance(Rectangle2d targetGoalRegion, Pose2d target, double fieldWidth, String alliance) {
        String cleaned = alliance.toLowerCase().strip();
        if (cleaned.equals("blue")) {
            return new Object[] { targetGoalRegion, target };
        } else {
            Pose2d redCenter = new Pose2d(fieldWidth - targetGoalRegion.getCenter().getX(), targetGoalRegion.getCenter().getY(), new Rotation2d(0, 0));
            Rectangle2d flippedToRed = new Rectangle2d(redCenter, targetGoalRegion.getXWidth(), targetGoalRegion.getYWidth());
            Pose2d redTarget = new Pose2d(fieldWidth - target.getX(), target.getY(), new Rotation2d(0, 0));
            return new Object[] { flippedToRed, redTarget };
        }
    }

    /* UTILITY FUNCTIONS FOR LIBRARY */
    public Pose2d getTarget(Pose2d robotPose) {
        if (targetGoalRegion.contains(robotPose.getTranslation())) {
            return target; 
        }

        // calculate distances to each passing target
        double leftDist = robotPose.getTranslation().getDistance(leftPassingTarget.getTranslation());
        double rightDist = robotPose.getTranslation().getDistance(rightPassingTarget.getTranslation());
        double middleDist = robotPose.getTranslation().getDistance(middlePassingTarget.getTranslation());

        // compare distances
        if (leftDist <= rightDist && leftDist <= middleDist) {
            return leftPassingTarget;
        } else if (rightDist <= leftDist && rightDist <= middleDist) {
            return rightPassingTarget;
        } else {
            return middlePassingTarget;
        }
    }

    public double getAngle(Pose2d robotPose) {
        boolean inRegion = targetGoalRegion.contains(robotPose.getTranslation()); 
        if (inRegion) {
            return targetLaunchAngle;
        } else {
            return passingLaunchAngle;
        }
    }

    public double getTargetHeight(Pose2d currentTarget) {
        if (currentTarget.equals(this.target)) {
            return this.targetHeight; 
        }
        return 0.0; // if passing, passing to the ground
    }
}